### ISSUE TITLE
Default value for rows missing CalculationDate.

### ISSUE THREAD

**Issue by nmb10** [franc3000/pipelines#12]
```sql
SELECT CalculationDate
FROM realtytrac_tax
WHERE RTPropertyUniqueIdentifier='386383';
```

```
|  0000-00-00  |
```
What value to use to compute LengthOfOwnership and HouseAge while computing derived fields from #5 for such rows?

**Comment by franc3000** [comment]
Can you create a default value for CalculationDate in the pipeline. If the date is 0000-00-00, use default of 2016-04-01

**Comment by nmb10** [comment]
Done.
